import { MusicTrack } from './types';

export const INITIAL_PLAYLIST: MusicTrack[] = [
  {
    id: 'udi-udi',
    title: 'Udi Udi',
    artist: 'DUELZONE Party Remix',
    album: 'Arcade Beats Vol. 1',
    audioUrl: '/music/udi-udi.mp3',
    coverGradient: 'from-amber-500 via-orange-600 to-red-600',
    icon: '🔥',
    genre: 'Party Beat',
  },
  {
    id: 'sheela-ki-jawani',
    title: 'Sheela Ki Jawani',
    artist: 'DUELZONE High-Energy Edition',
    album: 'Arena Dance Hits',
    audioUrl: '/music/sheela-ki-jawani.mp3',
    coverGradient: 'from-pink-500 via-rose-600 to-purple-700',
    icon: '💃',
    genre: 'Dance / Pop',
  },
  {
    id: 'chikni-chameli',
    title: 'Chikni Chameli',
    artist: 'DUELZONE Electro Club',
    album: 'Party Nights',
    audioUrl: '/music/chikni-chameli.mp3',
    coverGradient: 'from-yellow-400 via-amber-500 to-orange-600',
    icon: '⚡',
    genre: 'Electro Folk',
  },
  {
    id: 'barsaat',
    title: 'Barsaat',
    artist: 'DUELZONE Ambient Chill',
    album: 'Midnight Melodies',
    audioUrl: '/music/barsaat.mp3',
    coverGradient: 'from-blue-600 via-cyan-600 to-teal-700',
    icon: '🌧️',
    genre: 'Lo-Fi Chill',
  },
  {
    id: 'bairan',
    title: 'Bairan',
    artist: 'DUELZONE Synthwave',
    album: 'Retro Horizon',
    audioUrl: '/music/bairan.mp3',
    coverGradient: 'from-purple-600 via-violet-700 to-indigo-900',
    icon: '🌙',
    genre: 'Synthwave',
  },
  {
    id: 'sheesha',
    title: 'Sheesha',
    artist: 'DUELZONE Lounge Mix',
    album: 'VIP Arcade Lounge',
    audioUrl: '/music/sheesha.mp3',
    coverGradient: 'from-emerald-500 via-teal-600 to-cyan-800',
    icon: '💎',
    genre: 'Deep Lounge',
  },
  {
    id: 'khat',
    title: 'Khat',
    artist: 'DUELZONE Acoustic Session',
    album: 'Unplugged Arena',
    audioUrl: '/music/khat.mp3',
    coverGradient: 'from-rose-400 via-pink-600 to-red-700',
    icon: '✉️',
    genre: 'Acoustic Pop',
  },
];
